
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    CharacterController characterController;
    public float movementSpeed = 1;
    public float gravity = 9.8f;
    public float jumpHeight = 10.0f;
    public Transform cameraTransform;
    private float velocity = 0;




    private void Start()
    {
        characterController = GetComponent<CharacterController>();
    }

    void Update()
    {
        // player movement - forward, backward, left, right
        float horizontal = Input.GetAxis("Horizontal") * movementSpeed;
        float vertical = Input.GetAxis("Vertical") * movementSpeed;
        bool jumpInput = Input.GetKey("space");

        characterController.Move((cameraTransform.right * horizontal + cameraTransform.forward * vertical) * Time.deltaTime);

        // Gravity
        if (characterController.isGrounded)
        {
            velocity = 0;
        }
        else
        {
            velocity -= gravity * Time.deltaTime;
            characterController.Move(new Vector3(0, velocity, 0));
        }
        if (jumpInput && GetComponent<CharacterController>().isGrounded)
        {
            velocity += jumpHeight;

        }
    }
}